### ISSUE TITLE
Error processing queue

### ISSUE THREAD

**Issue by LeeCheneler** [frhagn/Typewriter#94] opened 2016-03-03 10:14 UTC
On all 1.3 releases we're only seeing a single file render (out of a lot) and the error messages that are appearing are as follows, it seems to differ based on trivial changes like to the file name:

> 09:47:42.273 ERROR: Error processing queue: Object reference not set to an instance of an object.
>    at Typewriter.Generation.Template.SetMappedSourceFile(ProjectItem item, String path)
>    at Typewriter.Generation.Template.SaveFile(File file, String output)
>    at Typewriter.Generation.Template.RenderFile(File file)
>    at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass5_0.<OnTemplateChanged>b__1()
>    at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()
> 

> 09:49:35.366 ERROR: Error processing queue: Exception has been thrown by the target of an invocation.
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
>    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
>    at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAPropertyInfo.set_Value(Object value)
>    at Typewriter.Generation.Template.SetMappedSourceFile(ProjectItem item, String path)
>    at Typewriter.Generation.Template.SaveFile(File file, String output)
>    at Typewriter.Generation.Template.RenderFile(File file)
>    at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass5_0.<OnTemplateChanged>b__1()
>    at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()

It seems that it is rendering the first file then breaking.

**Comment by frhagn** [comment] 2016-03-07 18:47
Looks like a problem with setting ths source file mapping.. Are you getting the error in an ASP.NET 5/Core project?

**Comment by LeeCheneler** [comment] 2016-03-09 10:36
Yes the project is currently on aspnet5 rc 1 update 1.

**Comment by frhagn** [comment] 2016-03-12 15:51
I've added a try/catch block around the `SetMappedSourceFile` call in 1.4 as a temporary workaround. 
Closing the issue as the problem is related to the lack of support for ASP.NET 5 which will be included in Typewriter 2.0.

**Closed by frhagn** 2016-03-12 15:51 UTC
